version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: pip
  directory: "/pkg"
  schedule:
    interval: weekly
- package-ecosystem: pip
  directory: "/web"
  schedule:
    interval: weekly
